
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.svisvi.jigsaw.init;

import net.svisvi.jigsaw.item.YamatopigItem;
import net.svisvi.jigsaw.item.YamatoSheathedItem;
import net.svisvi.jigsaw.item.YamatoSheathItem;
import net.svisvi.jigsaw.item.YamatoItem;
import net.svisvi.jigsaw.item.XrenoderItem;
import net.svisvi.jigsaw.item.UnbreakerItem;
import net.svisvi.jigsaw.item.TotemofshitItem;
import net.svisvi.jigsaw.item.TeethItem;
import net.svisvi.jigsaw.item.SusamoguscodestealItem;
import net.svisvi.jigsaw.item.SuperAutoForkItem;
import net.svisvi.jigsaw.item.SrucibleoffItem;
import net.svisvi.jigsaw.item.SrucibleItem;
import net.svisvi.jigsaw.item.SplashponosmutagenItem;
import net.svisvi.jigsaw.item.SolonkaItem;
import net.svisvi.jigsaw.item.SniperpromotionkitItem;
import net.svisvi.jigsaw.item.SmokingsuperpipeItem;
import net.svisvi.jigsaw.item.SlaveItem;
import net.svisvi.jigsaw.item.ShitgrenadeitemItem;
import net.svisvi.jigsaw.item.ShitgrenadeItem;
import net.svisvi.jigsaw.item.ShitammoItem;
import net.svisvi.jigsaw.item.ShitStormWandAdminItem;
import net.svisvi.jigsaw.item.ShitSnipeItem;
import net.svisvi.jigsaw.item.ShitGunItem;
import net.svisvi.jigsaw.item.ShitAmmoGunItem;
import net.svisvi.jigsaw.item.RickrollgunItem;
import net.svisvi.jigsaw.item.RadiohatItem;
import net.svisvi.jigsaw.item.PwhatItem;
import net.svisvi.jigsaw.item.PurgengunItem;
import net.svisvi.jigsaw.item.PurgenbundleItem;
import net.svisvi.jigsaw.item.PurgenbadItem;
import net.svisvi.jigsaw.item.PurgenammogunItem;
import net.svisvi.jigsaw.item.PurgenAmmoGunSniperItem;
import net.svisvi.jigsaw.item.PudgehookItem;
import net.svisvi.jigsaw.item.PoozookaItem;
import net.svisvi.jigsaw.item.PoopsRemoteItem;
import net.svisvi.jigsaw.item.PoopsItemItem;
import net.svisvi.jigsaw.item.PoopsItem;
import net.svisvi.jigsaw.item.PonoscutlassItem;
import net.svisvi.jigsaw.item.PonosSoundsItem;
import net.svisvi.jigsaw.item.PonosItem;
import net.svisvi.jigsaw.item.PiluleItem;
import net.svisvi.jigsaw.item.PigkaxeItem;
import net.svisvi.jigsaw.item.OnionItem;
import net.svisvi.jigsaw.item.NoFuelRocketItem;
import net.svisvi.jigsaw.item.NanomachinesItem;
import net.svisvi.jigsaw.item.MurasamsheathemptyItem;
import net.svisvi.jigsaw.item.MurasamsheathItem;
import net.svisvi.jigsaw.item.MurasamItem;
import net.svisvi.jigsaw.item.MerchantItem;
import net.svisvi.jigsaw.item.MedicgunItem;
import net.svisvi.jigsaw.item.MaznyaslayerItem;
import net.svisvi.jigsaw.item.MarmosetItem;
import net.svisvi.jigsaw.item.MagicJarItem;
import net.svisvi.jigsaw.item.LadleItem;
import net.svisvi.jigsaw.item.JumpingPantsItem;
import net.svisvi.jigsaw.item.JokerNoseItem;
import net.svisvi.jigsaw.item.JigsawbatteryItem;
import net.svisvi.jigsaw.item.JetstreamchairitemItem;
import net.svisvi.jigsaw.item.IronCanItem;
import net.svisvi.jigsaw.item.HitlermoustacheItem;
import net.svisvi.jigsaw.item.HighcompressedbeaweedItem;
import net.svisvi.jigsaw.item.HazmatItem;
import net.svisvi.jigsaw.item.FuelProcessRocketItem;
import net.svisvi.jigsaw.item.FriendshipventgItem;
import net.svisvi.jigsaw.item.FriendshipVentItem;
import net.svisvi.jigsaw.item.FoolDiscItem;
import net.svisvi.jigsaw.item.Flowergun1Item;
import net.svisvi.jigsaw.item.Flowergun0Item;
import net.svisvi.jigsaw.item.FishclockItem;
import net.svisvi.jigsaw.item.FatItem;
import net.svisvi.jigsaw.item.FargusfishItem;
import net.svisvi.jigsaw.item.EvokerfangsarmItem;
import net.svisvi.jigsaw.item.EggsItem;
import net.svisvi.jigsaw.item.DvoretskiyItem;
import net.svisvi.jigsaw.item.DristTntStickItem;
import net.svisvi.jigsaw.item.DelListItem;
import net.svisvi.jigsaw.item.DefuserItem;
import net.svisvi.jigsaw.item.DNAponosItem;
import net.svisvi.jigsaw.item.CockItem;
import net.svisvi.jigsaw.item.CockBellyItem;
import net.svisvi.jigsaw.item.ClownNoseItem;
import net.svisvi.jigsaw.item.CircusdiscItem;
import net.svisvi.jigsaw.item.CigaretteboxItem;
import net.svisvi.jigsaw.item.CigaretteItem;
import net.svisvi.jigsaw.item.CaptainbeaverItem;
import net.svisvi.jigsaw.item.CapitalbookItem;
import net.svisvi.jigsaw.item.BrownSoapItem;
import net.svisvi.jigsaw.item.BellyItem;
import net.svisvi.jigsaw.item.BeaweedteaItem;
import net.svisvi.jigsaw.item.BeaweedsoupItem;
import net.svisvi.jigsaw.item.BeaweedsheetincompleteItem;
import net.svisvi.jigsaw.item.BeaweednutconsumableItem;
import net.svisvi.jigsaw.item.BeaweeddustItem;
import net.svisvi.jigsaw.item.BeaweeddataItem;
import net.svisvi.jigsaw.item.BeaverzookaItem;
import net.svisvi.jigsaw.item.BeaverknifeItem;
import net.svisvi.jigsaw.item.BeavercollarItem;
import net.svisvi.jigsaw.item.BeaverbombItem;
import net.svisvi.jigsaw.item.BeaverbodyItem;
import net.svisvi.jigsaw.item.BeaveraxeItem;
import net.svisvi.jigsaw.item.BeaverammoItem;
import net.svisvi.jigsaw.item.BeaverItem;
import net.svisvi.jigsaw.item.AmpouleItem;
import net.svisvi.jigsaw.item.AdminkillerItem;
import net.svisvi.jigsaw.JigsawMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

public class JigsawModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, JigsawMod.MODID);
	public static final RegistryObject<Item> SLAVE_HELMET = REGISTRY.register("slave_helmet", () -> new SlaveItem.Helmet());
	public static final RegistryObject<Item> SLAVE_CHESTPLATE = REGISTRY.register("slave_chestplate", () -> new SlaveItem.Chestplate());
	public static final RegistryObject<Item> SLAVE_LEGGINGS = REGISTRY.register("slave_leggings", () -> new SlaveItem.Leggings());
	public static final RegistryObject<Item> SLAVE_BOOTS = REGISTRY.register("slave_boots", () -> new SlaveItem.Boots());
	public static final RegistryObject<Item> ADMINKILLER = REGISTRY.register("adminkiller", () -> new AdminkillerItem());
	public static final RegistryObject<Item> SOLONKA = REGISTRY.register("solonka", () -> new SolonkaItem());
	public static final RegistryObject<Item> PWHAT_HELMET = REGISTRY.register("pwhat_helmet", () -> new PwhatItem.Helmet());
	public static final RegistryObject<Item> P_WHATBLOCK = block(JigsawModBlocks.P_WHATBLOCK, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> PONOS_BUCKET = REGISTRY.register("ponos_bucket", () -> new PonosItem());
	public static final RegistryObject<Item> RICKROLLGUN = REGISTRY.register("rickrollgun", () -> new RickrollgunItem());
	public static final RegistryObject<Item> FLOWERGUN_0 = REGISTRY.register("flowergun_0", () -> new Flowergun0Item());
	public static final RegistryObject<Item> FLOWERGUN_1 = REGISTRY.register("flowergun_1", () -> new Flowergun1Item());
	public static final RegistryObject<Item> CIRCUSDISC = REGISTRY.register("circusdisc", () -> new CircusdiscItem());
	public static final RegistryObject<Item> BEAWEED = block(JigsawModBlocks.BEAWEED, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> BEAWEEDDUST = REGISTRY.register("beaweeddust", () -> new BeaweeddustItem());
	public static final RegistryObject<Item> BEAWEEDSOUP = REGISTRY.register("beaweedsoup", () -> new BeaweedsoupItem());
	public static final RegistryObject<Item> BEAVERBODY = REGISTRY.register("beaverbody", () -> new BeaverbodyItem());
	public static final RegistryObject<Item> BEAWEEDDUSTBLOCK = block(JigsawModBlocks.BEAWEEDDUSTBLOCK, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> CLOWN_NOSE_HELMET = REGISTRY.register("clown_nose_helmet", () -> new ClownNoseItem.Helmet());
	public static final RegistryObject<Item> COCK_CHESTPLATE = REGISTRY.register("cock_chestplate", () -> new CockItem.Chestplate());
	public static final RegistryObject<Item> TOTEMOFSHIT = REGISTRY.register("totemofshit", () -> new TotemofshitItem());
	public static final RegistryObject<Item> TEETH_HELMET = REGISTRY.register("teeth_helmet", () -> new TeethItem.Helmet());
	public static final RegistryObject<Item> CURSED_COW_SPAWN_EGG = REGISTRY.register("cursed_cow_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.CURSED_COW, -12045041, -7240829, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> NANOMACHINES_CHESTPLATE = REGISTRY.register("nanomachines_chestplate", () -> new NanomachinesItem.Chestplate());
	public static final RegistryObject<Item> BEAVERCOLLAR = REGISTRY.register("beavercollar", () -> new BeavercollarItem());
	public static final RegistryObject<Item> EVOKERFANGSARM = REGISTRY.register("evokerfangsarm", () -> new EvokerfangsarmItem());
	public static final RegistryObject<Item> PIGKAXE = REGISTRY.register("pigkaxe", () -> new PigkaxeItem());
	public static final RegistryObject<Item> FISHCLOCK = REGISTRY.register("fishclock", () -> new FishclockItem());
	public static final RegistryObject<Item> CAPITALBOOK = REGISTRY.register("capitalbook", () -> new CapitalbookItem());
	public static final RegistryObject<Item> PURGENBUNDLE = REGISTRY.register("purgenbundle", () -> new PurgenbundleItem());
	public static final RegistryObject<Item> PURGENGUN = REGISTRY.register("purgengun", () -> new PurgengunItem());
	public static final RegistryObject<Item> SHITAMMO = REGISTRY.register("shitammo", () -> new ShitammoItem());
	public static final RegistryObject<Item> SHIT_AMMO_GUN = REGISTRY.register("shit_ammo_gun", () -> new ShitAmmoGunItem());
	public static final RegistryObject<Item> PURGENAMMOGUN = REGISTRY.register("purgenammogun", () -> new PurgenammogunItem());
	public static final RegistryObject<Item> HITLERMOUSTACHE_HELMET = REGISTRY.register("hitlermoustache_helmet", () -> new HitlermoustacheItem.Helmet());
	public static final RegistryObject<Item> BELLY_CHESTPLATE = REGISTRY.register("belly_chestplate", () -> new BellyItem.Chestplate());
	public static final RegistryObject<Item> BEAVER_HELMET = REGISTRY.register("beaver_helmet", () -> new BeaverItem.Helmet());
	public static final RegistryObject<Item> BEAVER_CHESTPLATE = REGISTRY.register("beaver_chestplate", () -> new BeaverItem.Chestplate());
	public static final RegistryObject<Item> BEAVER_BOOTS = REGISTRY.register("beaver_boots", () -> new BeaverItem.Boots());
	public static final RegistryObject<Item> BEAVERBOMB = REGISTRY.register("beaverbomb", () -> new BeaverbombItem());
	public static final RegistryObject<Item> COCK_BELLY_CHESTPLATE = REGISTRY.register("cock_belly_chestplate", () -> new CockBellyItem.Chestplate());
	public static final RegistryObject<Item> PONOS_SOUNDS = REGISTRY.register("ponos_sounds", () -> new PonosSoundsItem());
	public static final RegistryObject<Item> FARGUSFISH = REGISTRY.register("fargusfish", () -> new FargusfishItem());
	public static final RegistryObject<Item> BEAVER_TOP = block(JigsawModBlocks.BEAVER_TOP, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> BEAVER_BOTTOM = block(JigsawModBlocks.BEAVER_BOTTOM, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> FOOL_DISC = REGISTRY.register("fool_disc", () -> new FoolDiscItem());
	public static final RegistryObject<Item> SHITTYBEE_SPAWN_EGG = REGISTRY.register("shittybee_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.SHITTYBEE, -2102515, -15727104, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> SHITTY_BEAR_SPAWN_EGG = REGISTRY.register("shitty_bear_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.SHITTY_BEAR, -12838138, -8414420, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> LIVING_BEAVER_SPAWN_EGG = REGISTRY.register("living_beaver_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.LIVING_BEAVER, -12773376, -65536, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> DN_APONOS = REGISTRY.register("dn_aponos", () -> new DNAponosItem());
	public static final RegistryObject<Item> HIGHCOMPRESSEDBEAWEED = REGISTRY.register("highcompressedbeaweed", () -> new HighcompressedbeaweedItem());
	public static final RegistryObject<Item> SPLASHPONOSMUTAGEN = REGISTRY.register("splashponosmutagen", () -> new SplashponosmutagenItem());
	public static final RegistryObject<Item> BEAVER_LIVE_COSTYL = block(JigsawModBlocks.BEAVER_LIVE_COSTYL, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> JOKER_NOSE_HELMET = REGISTRY.register("joker_nose_helmet", () -> new JokerNoseItem.Helmet());
	public static final RegistryObject<Item> SUPER_AUTO_FORK = REGISTRY.register("super_auto_fork", () -> new SuperAutoForkItem());
	public static final RegistryObject<Item> SNIPERPROMOTIONKIT = REGISTRY.register("sniperpromotionkit", () -> new SniperpromotionkitItem());
	public static final RegistryObject<Item> SNIPER_BEAVER_SPAWN_EGG = REGISTRY.register("sniper_beaver_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawModEntities.SNIPER_BEAVER, -12773376, -3342490, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> PURGEN_AMMO_GUN_SNIPER = REGISTRY.register("purgen_ammo_gun_sniper", () -> new PurgenAmmoGunSniperItem());
	public static final RegistryObject<Item> PURGENMAN_SPAWN_EGG = REGISTRY.register("purgenman_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.PURGENMAN, -11269108, -1, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> MURASAM = REGISTRY.register("murasam", () -> new MurasamItem());
	public static final RegistryObject<Item> MURASAMSHEATHEMPTY = REGISTRY.register("murasamsheathempty", () -> new MurasamsheathemptyItem());
	public static final RegistryObject<Item> MURASAMSHEATH = REGISTRY.register("murasamsheath", () -> new MurasamsheathItem());
	public static final RegistryObject<Item> LIVING_BEAVERLEGS_SPAWN_EGG = REGISTRY.register("living_beaverlegs_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawModEntities.LIVING_BEAVERLEGS, -12773376, -26368, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> LIVING_BEAVER_BODY_SPAWN_EGG = REGISTRY.register("living_beaver_body_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawModEntities.LIVING_BEAVER_BODY, -12773376, -6724096, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> BEAVERTOPOLIVECOSTYL = block(JigsawModBlocks.BEAVERTOPOLIVECOSTYL, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> BEAVERCUTCOSTYL = block(JigsawModBlocks.BEAVERCUTCOSTYL, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> BEAVERZOOKA = REGISTRY.register("beaverzooka", () -> new BeaverzookaItem());
	public static final RegistryObject<Item> BEAVERAMMO = REGISTRY.register("beaverammo", () -> new BeaverammoItem());
	public static final RegistryObject<Item> BEAVERBLOCK = block(JigsawModBlocks.BEAVERBLOCK, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> MERCHANT_HELMET = REGISTRY.register("merchant_helmet", () -> new MerchantItem.Helmet());
	public static final RegistryObject<Item> JETSTREAMCHAIR_SPAWN_EGG = REGISTRY.register("jetstreamchair_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.JETSTREAMCHAIR, -1, -1, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> JETSTREAMCHAIRITEM = REGISTRY.register("jetstreamchairitem", () -> new JetstreamchairitemItem());
	public static final RegistryObject<Item> GUNPOWDERBARREL = block(JigsawModBlocks.GUNPOWDERBARREL, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> DEFUSER = REGISTRY.register("defuser", () -> new DefuserItem());
	public static final RegistryObject<Item> SAFEGUNPOWDERBARREL = block(JigsawModBlocks.SAFEGUNPOWDERBARREL, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> BEAVERGUNPOWDERBARREL = block(JigsawModBlocks.BEAVERGUNPOWDERBARREL, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> SMOKINGSUPERPIPE = REGISTRY.register("smokingsuperpipe", () -> new SmokingsuperpipeItem());
	public static final RegistryObject<Item> BEAVERCOMPUTER = block(JigsawModBlocks.BEAVERCOMPUTER, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> MEDICGUN = REGISTRY.register("medicgun", () -> new MedicgunItem());
	public static final RegistryObject<Item> CIGARETTEBOX = REGISTRY.register("cigarettebox", () -> new CigaretteboxItem());
	public static final RegistryObject<Item> CIGARETTE = REGISTRY.register("cigarette", () -> new CigaretteItem());
	public static final RegistryObject<Item> CAPTAINBEAVER_HELMET = REGISTRY.register("captainbeaver_helmet", () -> new CaptainbeaverItem.Helmet());
	public static final RegistryObject<Item> EGGS = REGISTRY.register("eggs", () -> new EggsItem());
	public static final RegistryObject<Item> INVISIBILITY_WHEAT = block(JigsawModBlocks.INVISIBILITY_WHEAT, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> INVISIBILITY_WHEAT_BOTTOM = block(JigsawModBlocks.INVISIBILITY_WHEAT_BOTTOM, null);
	public static final RegistryObject<Item> WHEATPLACER = block(JigsawModBlocks.WHEATPLACER, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> INVISIBILITYBUSH = block(JigsawModBlocks.INVISIBILITYBUSH, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> SHITGRENADE = REGISTRY.register("shitgrenade", () -> new ShitgrenadeItem());
	public static final RegistryObject<Item> SHITGRENADEITEM = REGISTRY.register("shitgrenadeitem", () -> new ShitgrenadeitemItem());
	public static final RegistryObject<Item> POOPEMITTER_SPAWN_EGG = REGISTRY.register("poopemitter_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.POOPEMITTER, -10079488, -10079488, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> MARMOSET = REGISTRY.register("marmoset", () -> new MarmosetItem());
	public static final RegistryObject<Item> RADIO_BEAVER_SPAWN_EGG = REGISTRY.register("radio_beaver_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.RADIO_BEAVER, -12773376, -65536, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> RADIOHAT_HELMET = REGISTRY.register("radiohat_helmet", () -> new RadiohatItem.Helmet());
	public static final RegistryObject<Item> BEAWEEDTEA = REGISTRY.register("beaweedtea", () -> new BeaweedteaItem());
	public static final RegistryObject<Item> PURGENBAD = REGISTRY.register("purgenbad", () -> new PurgenbadItem());
	public static final RegistryObject<Item> BEAVERKNIFE = REGISTRY.register("beaverknife", () -> new BeaverknifeItem());
	public static final RegistryObject<Item> BEAVERAXE = REGISTRY.register("beaveraxe", () -> new BeaveraxeItem());
	public static final RegistryObject<Item> PUDGEHOOK = REGISTRY.register("pudgehook", () -> new PudgehookItem());
	public static final RegistryObject<Item> MAZNYASLAYER_HELMET = REGISTRY.register("maznyaslayer_helmet", () -> new MaznyaslayerItem.Helmet());
	public static final RegistryObject<Item> MAZNYASLAYER_CHESTPLATE = REGISTRY.register("maznyaslayer_chestplate", () -> new MaznyaslayerItem.Chestplate());
	public static final RegistryObject<Item> MAZNYASLAYER_LEGGINGS = REGISTRY.register("maznyaslayer_leggings", () -> new MaznyaslayerItem.Leggings());
	public static final RegistryObject<Item> SRUCIBLE = REGISTRY.register("srucible", () -> new SrucibleItem());
	public static final RegistryObject<Item> SRUCIBLEOFF = REGISTRY.register("srucibleoff", () -> new SrucibleoffItem());
	public static final RegistryObject<Item> JIGSAWBATTERY = REGISTRY.register("jigsawbattery", () -> new JigsawbatteryItem());
	public static final RegistryObject<Item> BEAWEEDSEEDS = block(JigsawModBlocks.BEAWEEDSEEDS, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> BEAWEEDSTAGE_1 = block(JigsawModBlocks.BEAWEEDSTAGE_1, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> BEAWEEDSTAGE_3 = block(JigsawModBlocks.BEAWEEDSTAGE_3, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> BEAWEEDSTAGE_4 = block(JigsawModBlocks.BEAWEEDSTAGE_4, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> BEAWEEDDATA = REGISTRY.register("beaweeddata", () -> new BeaweeddataItem());
	public static final RegistryObject<Item> BEAWEEDNUTCONSUMABLE = REGISTRY.register("beaweednutconsumable", () -> new BeaweednutconsumableItem());
	public static final RegistryObject<Item> BEAWEEDSHEETINCOMPLETE = REGISTRY.register("beaweedsheetincomplete", () -> new BeaweedsheetincompleteItem());
	public static final RegistryObject<Item> PILULE = REGISTRY.register("pilule", () -> new PiluleItem());
	public static final RegistryObject<Item> AMPOULE = REGISTRY.register("ampoule", () -> new AmpouleItem());
	public static final RegistryObject<Item> PONOSCUTLASS = REGISTRY.register("ponoscutlass", () -> new PonoscutlassItem());
	public static final RegistryObject<Item> JUMPING_PANTS_HELMET = REGISTRY.register("jumping_pants_helmet", () -> new JumpingPantsItem.Helmet());
	public static final RegistryObject<Item> JUMPING_PANTS_LEGGINGS = REGISTRY.register("jumping_pants_leggings", () -> new JumpingPantsItem.Leggings());
	public static final RegistryObject<Item> UNBREAKER = REGISTRY.register("unbreaker", () -> new UnbreakerItem());
	public static final RegistryObject<Item> HAZMAT_HELMET = REGISTRY.register("hazmat_helmet", () -> new HazmatItem.Helmet());
	public static final RegistryObject<Item> HAZMAT_CHESTPLATE = REGISTRY.register("hazmat_chestplate", () -> new HazmatItem.Chestplate());
	public static final RegistryObject<Item> HAZMAT_LEGGINGS = REGISTRY.register("hazmat_leggings", () -> new HazmatItem.Leggings());
	public static final RegistryObject<Item> HAZMAT_BOOTS = REGISTRY.register("hazmat_boots", () -> new HazmatItem.Boots());
	public static final RegistryObject<Item> ONION_HELMET = REGISTRY.register("onion_helmet", () -> new OnionItem.Helmet());
	public static final RegistryObject<Item> POOPS_ITEM = REGISTRY.register("poops_item", () -> new PoopsItemItem());
	public static final RegistryObject<Item> POOPS = REGISTRY.register("poops", () -> new PoopsItem());
	public static final RegistryObject<Item> MAGIC_JAR = REGISTRY.register("magic_jar", () -> new MagicJarItem());
	public static final RegistryObject<Item> SUSAMOGUSCODESTEAL = REGISTRY.register("susamoguscodesteal", () -> new SusamoguscodestealItem());
	public static final RegistryObject<Item> DVORETSKIY = REGISTRY.register("dvoretskiy", () -> new DvoretskiyItem());
	public static final RegistryObject<Item> DEL_LIST = REGISTRY.register("del_list", () -> new DelListItem());
	public static final RegistryObject<Item> FAT_BUCKET = REGISTRY.register("fat_bucket", () -> new FatItem());
	public static final RegistryObject<Item> FAT_BLOCK = block(JigsawModBlocks.FAT_BLOCK, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> TALLOW_BLOCK = block(JigsawModBlocks.TALLOW_BLOCK, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> BROWN_SOAP = REGISTRY.register("brown_soap", () -> new BrownSoapItem());
	public static final RegistryObject<Item> DRIST_TNT = block(JigsawModBlocks.DRIST_TNT, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> IRON_CAN = REGISTRY.register("iron_can", () -> new IronCanItem());
	public static final RegistryObject<Item> DRISTER_TNT_SPAWN_EGG = REGISTRY.register("drister_tnt_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.DRISTER_TNT, -13098238, -6392047, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> SLAVIC_TOTEM_RAW = block(JigsawModBlocks.SLAVIC_TOTEM_RAW, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> DRIST_TNT_STICK = REGISTRY.register("drist_tnt_stick", () -> new DristTntStickItem());
	public static final RegistryObject<Item> SHIT_STORM_WAND_ADMIN = REGISTRY.register("shit_storm_wand_admin", () -> new ShitStormWandAdminItem());
	public static final RegistryObject<Item> LADLE_AXE = REGISTRY.register("ladle_axe", () -> new LadleItem());
	public static final RegistryObject<Item> EMPTY_ROCKET_SPAWN_EGG = REGISTRY.register("empty_rocket_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.EMPTY_ROCKET, -16777216, -10079488, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> POOPS_ROCKET_SPAWN_EGG = REGISTRY.register("poops_rocket_spawn_egg", () -> new ForgeSpawnEggItem(JigsawModEntities.POOPS_ROCKET, -16777216, -10079488, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));
	public static final RegistryObject<Item> NO_FUEL_ROCKET = REGISTRY.register("no_fuel_rocket", () -> new NoFuelRocketItem());
	public static final RegistryObject<Item> FUEL_PROCESS_ROCKET = REGISTRY.register("fuel_process_rocket", () -> new FuelProcessRocketItem());
	public static final RegistryObject<Item> POOPS_REMOTE = REGISTRY.register("poops_remote", () -> new PoopsRemoteItem());
	public static final RegistryObject<Item> YAMATO = REGISTRY.register("yamato", () -> new YamatoItem());
	public static final RegistryObject<Item> YAMATO_SHEATHED = REGISTRY.register("yamato_sheathed", () -> new YamatoSheathedItem());
	public static final RegistryObject<Item> YAMATO_SHEATH = REGISTRY.register("yamato_sheath", () -> new YamatoSheathItem());
	public static final RegistryObject<Item> YAMATO_PIG = REGISTRY.register("yamato_pig", () -> new YamatopigItem());
	public static final RegistryObject<Item> LINEAR_PROJECTOR = block(JigsawModBlocks.LINEAR_PROJECTOR, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> XRENODER = REGISTRY.register("xrenoder", () -> new XrenoderItem());
	public static final RegistryObject<Item> SHIT_SNIPE = REGISTRY.register("shit_snipe", () -> new ShitSnipeItem());
	public static final RegistryObject<Item> SHIT_GUN = REGISTRY.register("shit_gun", () -> new ShitGunItem());
	public static final RegistryObject<Item> POOZOOKA = REGISTRY.register("poozooka", () -> new PoozookaItem());
	public static final RegistryObject<Item> SHIT_MISSILE = block(JigsawModBlocks.SHIT_MISSILE, JigsawModTabs.TAB_JIGSAW);
	public static final RegistryObject<Item> FRIENDSHIP_VENT = REGISTRY.register("friendship_vent", () -> new FriendshipVentItem());
	public static final RegistryObject<Item> FRIENDSHIP_VENT_G = REGISTRY.register("friendship_vent_g", () -> new FriendshipventgItem());
	public static final RegistryObject<Item> HITLER_EMITTER_SPAWN_EGG = REGISTRY.register("hitler_emitter_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawModEntities.HITLER_EMITTER, -6750157, -10079488, new Item.Properties().tab(JigsawModTabs.TAB_JIGSAW)));

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
