modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="jigsaw"
version="6.0.0"
displayName="jigsaw_things"
credits="Created by TemanSv1n"
displayURL="https://andrey-golovenchik.nethouse.ru/"
logoFile="logo.png"
authors="TemanSvin1, MCreator"
description='''
Strange shit mod
'''

[[dependencies.jigsaw]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.jigsaw]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

